name: Pull Request

on: [ pull_request ]

jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nodejs
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        run: npm ci

  unused-exports:
    name: Find unused exports (dead code)
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}

      - name: Run ts-prune
        run: npm ts-prune --error

    tests:
      name: Run the tests
      runs-on: ubuntu-latest
      needs: unused-exports

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Restore node_modules
          uses: actions/cache@v2
          with:
            path: node_modules
            key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}

        - name: Run test
          run: npm run test
